---
# tasks file for nexus
- name: Check if app directory exists
  stat:
    path: "/app/"
  register: directory_data

- name: Create app directory
  shell: 
    cmd: mkdir "{{dir}}"
  when: not directory_data.stat.exists
  
- name: Install nexus
  shell: 
    cmd: wget -O "{{dir}}"/nexus.tar.gz https://download.sonatype.com/nexus/3/latest-unix.tar.gz
  when: not directory_data.stat.exists

- name: Untar nexus downloaded file
  unarchive:
    src:  "{{dir}}/nexus.tar.gz"
    dest: "{{dir}}/"
    remote_src: true

- name: Rename untared file
  shell:
    cmd: mv /app/nexus-3* /app/nexus

- name: Create nexus user
  user: 
    name: nexus

- name: Change files ownership
  shell: "{{item}}"
  loop:
    - chown -R nexus:nexus /app/nexus
    - chown -R nexus:nexus /app/sonatype-work
    - sed -i 's/#run_as_user=.*/run_as_user="nexus"/' /app/nexus/bin/nexus.rc

- name: Create a nexus systemd unit file
  copy:
    src: "{{ src_file }}"
    dest: "{{ dest_file }}"

- name: Start nexus service
  service:
    name: nexus
    state: started
    enabled: true

